version = 1

test_patterns = [
    "\"tests/**\",",
    "\"test_*.py\","
]

exclude_patterns = [
    ".circleci/**",
    ".github/**",
    "datasets/**",
    "hypothesis/**",
    "implementation_tests/**",
    "misc/**"
]

[[analyzers]]
name = "python"
enabled = true

[analyzers.meta]
runtime_version = "3.x.x"

[[transformers]]
name = "yapf"
enabled = false

[[transformers]]
name = "autopep8"
enabled = false

[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "isort"
enabled = false
